routes:
  - name: junk_test
    path: /junk/test
    application: news
    table: junk_1
    request_model: TextInput

  - name: news_politics
    path: /news/politics
    application: news
    table: politics_1
    request_model: TextInput

  - name: news_technology
    path: /news/technology
    application: news
    table: technology_1
    request_model: TextInput

database: data/llm_data.db

