services:
  jaeger:
    image: jaegertracing/all-in-one:1.42
    environment:
      COLLECTOR_OTLP_ENABLED: "true"
    ports:
      - "16686:16686"  # Jaeger UI
      - "4317:4317"    # OTLP gRPC port
      - "4318:4318"    # OTLP HTTP port (not strictly needed for gRPC, but often exposed)
  
  fastapi-app:
    build: .
    container_name: fastapi-app
    ports:
      - "8000:8000"
    environment:
      # OTEL_EXPORTER_OTLP_TRACES_ENDPOINT points to our Jaeger service (OTLP gRPC port).
      OTEL_EXPORTER_OTLP_TRACES_ENDPOINT: "http://jaeger:4317"
      OTEL_EXPORTER_OTLP_TRACES_PROTOCOL: "grpc"
      APIKEY: ${APIKEY}
    depends_on:
      - jaeger
