global:
  scrape_interval: 15s  # How frequently Prometheus scrapes metrics

alerting:
  alertmanagers:
    - static_configs:
        - targets: ['alertmanager:9093']

scrape_configs:
  - job_name: 'fastapi'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['backend:8000']  # 'backend' is the service name in docker-compose.yml

  - job_name: 'jaeger'
    scrape_interval: 10s
    metrics_path: '/metrics'
    static_configs:
      - targets: ['jaeger:14269']  # Jaeger metrics endpoint

rule_files:
  - "alerts.yml"
